apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-notes-test
  labels:
    env: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-notes
      env: test
  template:
    metadata:
      labels:
        app: fastapi-notes
        env: test
    spec:
      containers:
      - name: fastapi-container
        image: dilnazkamil/fastapi-notes:test
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service-test
spec:
  selector:
    app: fastapi-notes
    env: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort  
